#!/bin/sh
# .ENVRC --environment initialisation for sh(1) compatible shells
#
# Contents:
# dirs_not_in_path() --Return a path-spec of "new" path elements.
# $*                 --the list of directories to be added to the path
# prepend_path()     --Merge two path-spec.s as a ":" separated list.
#
# Remarks:
# TODO: cleanup old crufty definitions.

#
# dirs_not_in_path() --Return a path-spec of "new" path elements.
#
# Parameters:
# path --the current value of path
# $*   --the list of directories to be added to the path
#
dirs_not_in_path()
{
    local path=":$1:"; shift
    local dirs=''

    for dir in "$@"; do
	case "$path" in
	*:$dir:*)
	    ;;		# already in the path
	*)
	    if [ -d "$dir" ]; then
		dirs="$dirs:$dir"
	    fi
	    ;;
	esac
    done
    echo ${dirs#:}      # trim initial ':'
}

#
# prepend_path() --Merge two path-spec.s as a ":" separated list.
#
prepend_path()
{
    local path="$(dirs_not_in_path "$@"):$1"

    echo "${path#:}"    # trim initial ':'
}

#
# Initial setups: get host, os, and arch using the "standard" path,
# then go hunting for some more paths.
#
sys_path="$PATH"
PATH=/bin:/usr/bin
export SESSION_START="$(date '+.envrc: %c')"
#echo $SESSION_START >&2

export HOSTNAME=${HOSTNAME:-$(uname -n)}
export ARCH=${ARCH:-$(uname -m|sed -e 's/i.86/i386/')}
export OS=${OS:-$(uname -s | tr A-Z a-z | sed -e 's/-[.0-9]*//')}

PATH=$(prepend_path "$sys_path" \
    . $HOME/bin $HOME/bin/$OS-$ARCH \
    $HOME/local/bin $HOME/local/bin/$OS-$ARCH \
    /usr/local/*bin /usr/local/*/bin \
    /usr/local/opt/coreutils/libexec/gnubin \
    /Applications/MacPorts/*/Contents/MacOS/bin \
    /opt/local/libexec/gnubin /opt/*/sbin /opt/*/bin \
    /usr/*bin /*bin /usr/games \
    /opt/local/Library/Frameworks/Python.framework/Versions/Current/bin)
export LD_LIBRARY_PATH=$(prepend_path "$LD_LIBRARY_PATH" \
    $HOME/local/lib /usr/local/lib /opt/local/lib \
    /usr/lib /usr/X11R6/lib)

#export CDPATH=$(prepend_path "$CDPATH" . .. $HOME/Projects $HOME/github)

export MANPATH=$(prepend_path "$MANPATH" \
    $HOME/local/man:$HOME/local/share/man \
    /usr/local/man /usr/local/share/man /usr/local/*/man \
    /usr/local/opt/coreutils/libexec/gnuman \
    /Applications/MacPorts/*/Contents/Resources/man \
    /opt/local/libexec/gnubin/man /opt/*/share/man /opt/share/man \
    /usr/*/man /usr/man)
#
# Forget the path manipulation routines prepend_path(), dirs_not_in_path();
# they're not needed any more.
#
unset prepend_path
unset dirs_not_in_path
unset sys_path

#
# TMPDIR defaults to $HOME/tmp, if it exists.
#
if [ -f $HOME/tmp ]; then
    export TMPDIR="$HOME/tmp"
fi

#
# Settings for paginated output with less(1).
# Also, if there's a lesspipe filter, setup to use it.
#
export PAGER=less
export LESS='--LONG-PROMPT --ignore-case --RAW-CONTROL-CHARS --use-color --quit-if-one-screen'
if [ -x "$HOME/bin/lesspipe" ]; then
    export LESSOPEN="|$HOME/bin/lesspipe %s"
fi
# map underline to italics
export LESS_TERMCAP_us=$(printf '\033[3m')
export LESS_TERMCAP_ue=$(printf '\033[m')

#
# Colour options for listing files and directories with ls(1):
#
# directory           di=1         bold
# symlink             ln=36        cyan
# multiple hard links mh=4;36      underlined, cyan (not always supported...)
# pipe                pi=32        yellow
# socket              so=32
# door                do=32
# block device        bd=1;35      bold, magenta
# char device         cd=1;35
# orphaned symlink    or=5;36      blinking, cyan
# setuid              su=35        magenta
# setgid              sg=35
# capability          ca=35
# writable+sticky     tw=30;45     white/magenta
# writable by others  ow=31        red
# sticky              st=35        magenta
# executable          ex=32        green
#
# backup files        *~=38;05;8   grey (256 colour)
#
export LS_COLORS='di=1:ln=36:pi=32:so=32:do=32:bd=1;35:cd=1;35'
       LS_COLORS="$LS_COLORS:or=5;36:su=35:sg=35:ca=35"
       LS_COLORS="$LS_COLORS:tw=30;45:ow=31:st=35:ex=32"
       LS_COLORS="$LS_COLORS:*~=38;05;8:*.bak=38;05;8"

#
# Define ANSI colours for logging with LOG_COLORS.
#
export LOG_COLORS='debug=36:notice=1:warning=1;33:err=1;31:crit=1;33;41:alert=1;5;33;41:emerg=1;5;37;41'

#
# Colour options for displaying matches in grep(1):
#
# ms --match selection			(default: 01;31)
# mc --match in context, if -v		(default: 01;31)
# mt --match text ( =ms,mc)
# sl --selected line
# cx --context line
# fn --filename				(default: 35)
# ln --line number			(default: 32)
# bn --byte number			(default: 32)
# se --separator			(default: 36)
#
export GREP_COLORS='mt=1;33:cx=2:fn=36'
export ACK_OPTIONS="--color-match=cyan --color-filename=bold --color-lineno=yellow --nogroup"

#
# development settings...
#
export EDITOR=vi
#export CC=gcc
export MAKESHIFT_HOME=/usr/local
export prefix=/usr/local
export VCS=git
export PERL5LIB=/usr/local/lib/perl5
export PYTHONPATH=/usr/local/lib/python
export RSYNC_RSH=ssh

#
# X11 environment configuration, if any.
#
# X11 setups are mostly done from the .displayrc file, which contains
# the prevailing values if a session is currently open, and doesn't
# exist when there is no current X11 session.
#
if [ -f "$HOME/.displayrc" ]; then
    . "$HOME/.displayrc"
fi
export XFILESEARCHPATH="$HOME/lib/X11/1024x768/%N:/usr/X11R6/lib/X11/%T/%N"

#
# Per-host initialisation, if any.
#
if [ -f $HOME/.envrc-$HOSTNAME ] ; then
    . $HOME/.envrc-$HOSTNAME
fi
