#!/bin/sh
# define function/aliases...
#
env()	{ command env | cat -v | sort; }
path()  { eval "echo \${${1:-PATH}}" | tr ':' '\012';  }
less4()	{ less -x4 $*; }

find0() { find "$@" -print0; }

#
# recursively() --Run a command on all files in this directory and subdirs.
#
recursively() { find [^.]* -type f -print0 | xargs -0 "$@"; }

#
# quietly() --Run a command, discarding stdout+stderr.
#
quietly() { "$@"; } >/dev/null 2>&1

#
# calc() --Echo a calculation result.
#
calc() { echo "scale=2; $*" | bc; }
#
# maxlen() --Calculate the maximum line length of stdin
#
maxlen() { sed -e 's/./+1/g' -e 's/^/0/'| bc | sort -rn | head -1; }

#
# pdfman() --Open a man page as a PDF file.
#
pdfman() {
    man -t "$@" | ps2pdf - - > /tmp/$1.pdf
    open /tmp/$1.pdf
    { sleep 2; rm /tmp/$1.pdf; } &
}

#
# tgrep() --"table" grep; print the first (header) line, and matching others.
#
tgrep() { local tag=$1; shift; cat "$@" |sed -ne1p -e "/$tag/p"; }
