#!/bin/sh
# PROFILE --login commands.
#
# Contents:
# load_file() --Load a file, with logging.
#
# Remarks:
# The profile guesses at the shell, and sets up the "ENV" variable
# appropriately (e.g. .shrc, .bashrc, .kshrc etc.)
# Beware:
#  * Ubuntu lightdm-session ignores your login-shell, and runs it via /bin/sh
#  * cygwin's ps command is broken, so we do a fallback to bash.
#
date "+# .profile: ${HOSTNAME:-unknown} %c" >&2
export BASH_SILENCE_DEPRECATION_WARNING=1       # suppress suppress Darwin messages

#
# load_file() --Load a file, with logging.
#
load_file()
{
    for file; do
	case "$file" in
	    /*) ;;		# already an absolute filename
	    *) file=$HOME/$file;;
	esac
	if [ -e $file ]; then
	    printf "# loading %s\n" "$file" >&2
	    builtin . $file
	fi
    done
}

shell=$(ps -o comm= $$ 2>/dev/null | sed -e 's/^-//') # guess current shell
export ENV=${ENV:-$HOME/.${shell:-bash}rc}	# fallback to bash

alias .='load_file'
load_file .ttyrc .displayrc $ENV
unset shell load_file
unalias .

#
# Gnome terminal seems a bit buggy wrt its cursor, which seems to
# disappear(!) often.  The following command string sets its colour
# (not possible any other way), which has the useful side-effect
# of making it visible again.
#
if [ "$DESKTOP_SESSION" = "gnome-classic" \
     -o "$SESSIONTYPE" = "gnome-session" ]; then
    printf '\033]12;red\a'	# gnome: set red cursor (erk!)
fi
if [ $(uname -s) != 'Darwin' ]; then
    printf '\033]6;\007\033]7;\007' # disable apple-term's represented file stuff
fi

if type fortune 2>&1 >/dev/null; then fortune; fi
