#!/bin/sh
# .KSHRC (->.BASHRC) --RC file for KSH (and BASH)
#
#date "+.bashrc: %c"
if [ ! "$PS1" ]; then
    return
fi
test -f /etc/bashrc && . /etc/bashrc
test -z "$ENV_START" && . "$HOME/.envrc"
test -f "$HOME/.ttyrc" && . "$HOME/.ttyrc"
test -f "$HOME/.funcrc" && . "$HOME/.funcrc"

umask 002
set -o ignoreeof	# ignore <CTRL d>, use exit to terminate ksh
set -o emacs		# Set up in-line edit

# 
# Set main prompt.  Note, this prompt is syntactally a shell nop,
# so complete lines can be selected and pasted for re-execution.
#
case `hostname` in
    kyogen*)     fg=32;;	# green
    zeno*)      fg=36;;	# cyan
    *)		fg=33;;	# yellow
esac
case `id` in
    uid=0*)     fg=33; bg=41;;	# yellow/red
    *)		bg=;;	# unset...
esac
if [ "$bg" != "" ]; then
    mode="\e[${fg};${bg};1m"
else
    mode="\e[${fg};1m"
fi
case "$TERM" in
    xterm*|rxvt*|dtterm*|cygwin)	# title-bar displays user+host+directory
        PS1="\[\e]1;\h\a\e]2;\u@\h \w\a\]: [\[$mode\]\h\[\e[m\]]; "
        PS2="\[\e[36m\]: > \[\e[;m\]"
	window_title()
	{
	    printf "\033]2;"
	    printf "$@"
	    printf "\007"
	} >/dev/tty
	;;
    ansi|linux|vt[0-9]*)	# colourful prompt only
        PS1=": [\[$mode\]\h\[\e[m\]]; "
        PS2="\[\e[36m\]: > \[\e[;m\]"
	;;
    *)				# display hostname in prompt
        PS1=': [\h]; '
	PS2=': > '
	;;
esac
#EOF
