#!/bin/sh
# .KSHRC (->.BASHRC) --RC file for KSH (and BASH)
#
#date "+.bashrc: %c"
if [ ! "$PS1" ]; then
    return
fi
umask 002
set -o ignoreeof	# ignore <CTRL d>, use exit to terminate ksh
set -o emacs		# Set up in-line edit
HISTCONTROL=ignoreboth		# bash history control
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

test -f /etc/bashrc && . /etc/bashrc # REVISIT: is this needed?
test -z "$ENV_START" && . "$HOME/.envrc"
test -f "$HOME/.ttyrc" && . "$HOME/.ttyrc"
test -f "$HOME/.funcrc" && . "$HOME/.funcrc"

# 
# Set main prompt.  Note, this prompt is syntactally a shell nop,
# so complete lines can be selected and pasted for re-execution.
#
if [ "$VCS" = "git" ]; then
    vcs_prompt="\$(git branch 2>/dev/null|sed -ne '/^[*]/s/^[*] */:/p')"
fi

case $HOSTNAME in
    joshu)	fg=32;;		# green: development
    kyogen)	fg=32;;
    tutsplus)	fg=33;;		# yellow: production
    creattica)	fg=33;;
    *)		fg=36;;		# cyan: other
esac
case $(id) in
    uid=0*)     fg=33; bg=41;;	# yellow/red
    *)		bg=;;	# unset...
esac
if [ "$bg" != "" ]; then
    mode="\e[${fg};${bg};1m"
else
    mode="\e[${fg};1m"
fi
case "$TERM" in
    xterm*|rxvt*|dtterm*|cygwin)	# title-bar displays user+host+directory
        PS1="\[\e]1;\h\a\e]2;\u@\h \w\a\]: [\[$mode\]\h$vcs_prompt\[\e[m\]]; "
        PS2="\[\e[36m\]: > \[\e[;m\]"
	window_title()
	{
	    printf "\033]2;"
	    printf "$@"
	    printf "\007"
	} >/dev/tty
	;;
    ansi|linux|vt[0-9]*)	# colourful prompt only
        PS1=": [\[$mode\]\h$vcs_prompt\[\e[m\]]; "
        PS2="\[\e[36m\]: > \[\e[;m\]"
	;;
    *)				# display hostname in prompt
        PS1=': [\h$vcs_prompt]; '
	PS2=': > '
	;;
esac

cd .				# ...let RVM do its thing

#
# load host-specific rc file
#
if [ -f $HOME/$ENV-$HOSTNAME ]; then
    . $HOME/$ENV-$HOSTNAME
fi
