#!/bin/sh
# .ENVRC --environment initialisation for sh(1) compatible shells
#
# Contents:
# dirs_not_in_path() --Return a path-spec of "new" path elements.
# prepend_path()     --Merge two path-spec.s as a ":" separated list.
# less:              --Settings for paginated output.
# ls:                --Colour options for listing files and directoriesl
# .displayrc:        --X11 environment configuration, if any.
# .envrc-hostname:   --per-host initialisation, if any.
# 
export ENV_START=$(date "+.envrc: %c")
#echo $ENV_START >&2

export HOSTNAME=$(uname -n)
export ARCH=$(uname -m|sed -e "s/i.86/i386/")
export OS=$(uname -s | tr '[A-Z]' '[a-z]')
export USER=${USER:-$LOGNAME}
if [ -f $HOME/tmp ]; then
    export TMPDIR;     TMPDIR="$HOME/tmp"
fi

#
# dirs_not_in_path() --Return a path-spec of "new" path elements.
#
dirs_not_in_path() 
{
    local path=$1; shift
    for dir in "$@"; do
	case "$path" in
	$dir:*)		;;		# already at start of path
	*:$dir:*)	;;		# already in the middle of path
	*:$dir)		;;		# already at the end of path
	*)
	    if [ -d "$dir" ]; then
		echo $dir
	    fi
	    ;;
	esac
    done |
    {					# echo ":" separated list of items
	read d && printf '%s' "$d"
	while read d; do
	    printf ':%s' "$d"
	done
    }
}

#
# prepend_path() --Merge two path-spec.s as a ":" separated list.
#
prepend_path()
{
    local prefix=$(dirs_not_in_path "$@")
    if [ "$1" -a "$prefix" ]; then
	echo "$prefix:$1"
    elif [ "$1" -o "$prefix" ]; then
	echo "$prefix:$1"
    fi
}

export PATH;
PATH=$(prepend_path $PATH \
    . $HOME/bin $HOME/bin/$OS-$ARCH \
    $HOME/local/bin $HOME/local/bin/$OS-$ARCH \
    /usr/local/*bin /usr/local/opt/coreutils/libexec/gnubin \
    /opt/local/libexec/gnubin /opt/*/bin /*bin /usr/*bin\
    $HOME/local/libexec /usr/local/libexec /opt/*/libexec)

export LD_LIBRARY_PATH=$(prepend_path "$LD_LIBRARY_PATH" \
    $HOME/local/lib /usr/local/lib /opt/local/lib \
    /usr/lib /usr/X11R6/lib )

export CDPATH=$(prepend_path "$CDPATH" . .. $HOME/Projects $HOME/github)

export MANPATH=$(prepend_path "$MANPATH" \
    $HOME/local/man:$HOME/local/share/man \
    usr/local/man /usr/local/share/man /usr/local/*/man \
     /usr/local/opt/coreutils/libexec/gnuman \
    /opt/*/share/man /opt/share/man \
    /usr/*/man /usr/man)

#
# less: --Settings for paginated output.
#
export LESS=-MiRFX
export LESSCHARSET=latin1
if [ -x "$HOME/bin/lesspipe" ]; then
    export LESSOPEN="|$HOME/bin/lesspipe %s"
fi

#
# ls: --Colour options for listing files and directoriesl
# 
# directory           di=1         bold
# symlink             ln=36        cyan
# multiple hard links mh=4;36      underlined, cyan (not always supported...)
# pipe                pi=32        yellow
# socket              so=32
# door                do=32
# block device        bd=1;35      bold, magenta
# char device         cd=1;35
# orphaned symlink    or=5;36      blinking, cyan
# setuid              su=35        magenta
# setgid              sg=35
# capability          ca=35
# writable+sticky     tw=31;45     red/magenta
# writable by others  ow=31        red
# sticky              st=35        magenta
# executable          ex=32        green
#
# backup files        *~=34        blue
#
export LS_COLORS='di=1:ln=36:pi=32:so=32:do=32:bd=1;35:cd=1;35'
       LS_COLORS="$LS_COLORS:or=4;36:su=35:sg=35:ca=35"
       LS_COLORS="$LS_COLORS:tw=31;45:ow=31:st=35:ex=32"
#       LS_COLORS="$LS_COLORS:*~=34:*.bak=34"
       LS_COLORS="$LS_COLORS:*~=38;05;8:*.bak=38;05;8"
       LS_COLORS="$LS_COLORS:ec=\e[m"

export LOG_COLORS='debug=36:notice=1:warning=1;33:err=1;31:crit=1;33;41:alert=1;5;33;41:emerg=1;5;37;41'

export EDITOR=vi
export GREP_OPTIONS=--color=auto
export GREP_COLOR=36		# cyan
export ACK_OPTIONS="--color-match=cyan --color-filename=bold --color-lineno=yellow --nogroup"
export PAGER=less

export WIRESHARK_APP_DIR=/Applications/Extras

#
# development settings...
#
export CC=gcc
export prefix=/usr/local
export DEVKIT_HOME=/usr/local
export VCS=git
export PERL5LIB=$prefix/lib/perl5
# export CVSROOT=:ext:cvs:/home/CVS	# CVS: those were the days, huh?
# export CVS_RSH=ssh
export RSYNC_RSH=ssh

export LARCH_PATH=/usr/local/share/splint/lib
export LCLIMPORTDIR=/usr/local/share/splint/imports

export SVN_EDITOR=/usr/local/bin/svn-edit
#export SVN_ROOT=svn+ssh://somehost/srv/svn
export SVN_ROOT=file://$HOME/svn

#
# .displayrc: --X11 environment configuration, if any.
# 
# X11 setups are mostly done from the .displayrc file, which contains
# the prevailing values if a session is currently open, and doesn't
# exist when there is no current X11 session.
#
if [ -f "$HOME/.displayrc" ]; then
    . "$HOME/.displayrc"
fi
export XFILESEARCHPATH="$HOME/lib/X11/1024x768/%N:/usr/X11R6/lib/X11/%T/%N"

#
# .envrc-hostname: --per-host initialisation, if any.
#
if [ -f $HOME/.envrc-$HOSTNAME ] ; then
    . $HOME/.envrc-$HOSTNAME
fi
