#!/bin/sh
# .ENVRC --environment initialisation for sh(1) compatible shells
#
# REVISIT: modernise export declarations.
# 
ENV_START=$(date "+.envrc: %c"); export ENV_START
#echo $ENV_START

export ARCH;	
       ARCH=$(uname -m|sed -e "s/i.86/i386/")
export OS;
       OS=$(uname -s | tr '[A-Z]' '[a-z]')
#
# addpath() --Selectively add entries to PATH 
#
# REVISIT: avoid multiple evals
addpath() 
{
    local pathvar=$1; shift
    for p in "$@"; do
        test -d "$p" && eval $pathvar='$'$pathvar:$p
    done
}

export PATH;
       PATH=.
addpath PATH $HOME/bin $HOME/bin/$OS-$ARCH
addpath PATH $HOME/local/bin $HOME/local/bin/$OS-$ARCH

addpath PATH /usr/local/*bin /opt/*/bin /*bin /usr/*bin

addpath PATH /usr/java/bin /usr/local/java/bin

addpath PATH /cygdrive/c/WINDOWS/system32 /cygdrive/c/WINDOWS /cygdrive/c/WINDOWS/system32/Wbem
addpath PATH /usr/local/libexec /opt/*/libexec

export PLAN9=/usr/local/plan9
addpath PATH $PLAN9/bin

export CC;
       CC=gcc
export EDITOR;
    EDITOR=vi

unset LANG
export LD_LIBRARY_PATH;
       LD_LIBRARY_PATH=$HOME/local/lib:/usr/local/lib;
addpath LD_LIBRARY_PATH /opt/local/lib
addpath LD_LIBRARY_PATH /usr/lib /usr/X11R6/lib 
export CDPATH;     
       CDPATH=.
addpath CDPATH ../ $HOME/Projects $HOME/github

export MANPATH; 
       MANPATH=$HOME/man:$HOME/local/man:$HOME/local/share/man

addpath MANPATH /opt/*/share/man /opt/share/man
addpath MANPATH /usr/local/man /usr/local/share/man /usr/local/*/man
addpath MANPATH /usr/share/man /usr/man /usr/java/man

export HOSTNAME;
       HOSTNAME=$(uname -n)

export LESS;
       LESS=-MiR
export LESSCHARSET
       LESSCHARSET=latin1
if [ -x "$HOME/bin/lesspipe" ]; then
    export LESSOPEN
           LESSOPEN="|$HOME/bin/lesspipe %s"
fi
#
# Colour options for LS:
# directory           di=1         bold
# symlink             ln=36        cyan
# multiple hard links mh=4;36      underlined, cyan (not always supported...)
# pipe                pi=32        yellow
# socket              so=32
# door                do=32
# block device        bd=1;35      bold, magenta
# char device         cd=1;35
# orphaned symlink    or=5;36      blinking, cyan
# setuid              su=35        magenta
# setgid              sg=35
# capability          ca=35
# writable+sticky     tw=31;45     red/magenta
# writable by others  ow=31        red
# sticky              st=35        magenta
# executable          ex=32        green
#
# backup files        *~=34        blue
#
export LS_COLORS;
       LS_COLORS='di=1:ln=36:pi=32:so=32:do=32:bd=1;35:cd=1;35'
       LS_COLORS="$LS_COLORS:or=4;36:su=35:sg=35:ca=35"
       LS_COLORS="$LS_COLORS:tw=31;45:ow=31:st=35:ex=32"
#       LS_COLORS="$LS_COLORS:*~=34:*.bak=34"
       LS_COLORS="$LS_COLORS:*~=38;05;8:*.bak=38;05;8"
       LS_COLORS="$LS_COLORS:ec=\e[m"

export LOG_COLORS;
       LOG_COLORS='debug=36:notice=1:warning=1;33:err=1;31:crit=1;33;41:alert=1;5;33;41:emerg=1;5;37;41'

export GREP_OPTIONS;
       GREP_OPTIONS=--color=auto
export GREP_COLOR;
       GREP_COLOR=36		# cyan

export PAGER;	PAGER=less
#export TERM;	TERM=xterm
export USER;	USER=${USER:-$LOGNAME}
if [ -f $HOME/tmp ]; then
    export TMPDIR;     TMPDIR="$HOME/tmp"
fi
#
# X11 setups are mostly done from the .displayrc file, which contains
# the prevailing values if a session is currently open, and doesn't
# exist when there is no current X11 session.
#
test -f "$HOME/.displayrc" && . "$HOME/.displayrc"
export XFILESEARCHPATH;
XFILESEARCHPATH="$HOME/lib/X11/1024x768/%N:/usr/X11R6/lib/X11/%T/%N"

export WIRESHARK_APP_DIR;
       WIRESHARK_APP_DIR=/Applications/Extras

#
# development settings...
#
export prefix=/usr/local
export DEVKIT_HOME=/usr/local
export VCS=git

export PERL5LIB=$prefix/lib/perl5

# export CVSROOT=:ext:cvs:/home/CVS
# export CVS_RSH=ssh
export RSYNC_RSH=ssh

export LARCH_PATH=/usr/local/share/splint/lib
export LCLIMPORTDIR=/usr/local/share/splint/imports

export SVN_EDITOR=/usr/local/bin/svn-edit
#export SVN_ROOT=svn+ssh://somehost/srv/svn
export SVN_ROOT=file://$HOME/svn

#
# RVM: --Ruby Version Manager
#
if [ "$rvm_bin_path" ] ; then
    addpath PATH $rvm_bin_path
#     . $rvm_path/scripts/rvm
fi

#
# .envrc-hostname: --per-host initialisation, if any.
#
if [ -f $HOME/.envrc-$HOSTNAME ] ; then
    . $HOME/.envrc-$HOSTNAME
fi
