#!/bin/sh
# PROFILE --login commands.
#
# Remarks:
# The profile guesses at the shell, and sets up the "ENV" variable
# appropriately (e.g. .shrc, .bashrc, .kshrc etc.)
# Beware:
#  * Ubuntu lightdm-session ignores your login-shell, and runs it via /bin/sh
#  * cygwin's ps command is broken, so we do a fallback to bash.
#
#date "+.profile: %c"

load_files()
{
    for file; do
	if [ -f $file ]; then
	    # printf "loading %s\n" "$file" >&2
	    . $file
	fi
    done
}

shell=$(ps -o comm= $$ 2>/dev/null | sed -e 's/^-//') # guess current shell
export ENV=${ENV:-$HOME/.${shell:-bash}rc}	# fallback to bash

load_files $HOME/.envrc $HOME/.ttyrc $HOME/.displayrc $ENV
unset shell load_files
