"
" .VIMRC --vim config file
"
set autoindent				"Preserve current indent on new lines
set textwidth=78			"Wrap at column 78
set backspace=indent,eol,start		"Make backspaces delete sensibly

set tabstop=8				"If a tab appears, it's (up to) 8 spaces
set shiftwidth=4			"indent/outdent by four columns
set expandtab				"Convert all tabs typed to spaces

set matchpairs+=<:>			"Allow % to bounce between "<", ">"

if has("mouse")
    set mouse=a

" Syntax highlighting customisations.
set t_Co=256				" force "256 colour" mode
syntax on
:colorscheme custom

" Show syntax highlighting groups for word under cursor
nmap <C-S-P> :call <SID>SynStack()<CR>
function! <SID>SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc
endif
