"
" .VIMRC --vim config file
"
set autoindent				"Preserve current indent on new lines
set textwidth=78			"Wrap at column 78
set backspace=indent,eol,start		"Make backspaces delete sensibly

set tabstop=8				"If a tab appears, it's (up to) 8 spaces
set shiftwidth=4			"indent/outdent by four columns
set expandtab				"Convert all tabs typed to spaces

set matchpairs+=<:>			"Allow % to bounce between "<", ">"
"
" template-insertion abbrev.s
"
iab papp :r /usr/local/share/template/main.pl
iab pmod :r /usr/local/share/template/module.pm
