#!/bin/sh
# .ENVRC --environment initialisation for sh(1) compatible shells
#
ENV_START=`date "+.envrc: %c"`; export ENV_START
#echo $ENV_START
#
# The following SSH code may not be needed, but sshLogin seems flaky...
#
#ssh_pid=`ps -x|grep ssh-agent|grep -v grep|awk '{print $1;}'`
#if [ -z "$ssh_pid" ]; then
#    echo ".envrc: no ssh-agent"
#    eval `ssh-agent`
#    (
#        echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK; export SSH_AUTH_SOCK"
#        echo "SSH_AGENT_PID=$SSH_AGENT_PID; export SSH_AGENT_PID"
#    ) > $HOME/.sshrc
#    ssh-add </dev/null
#else
#    echo ".envrc: found ssh-agent: $ssh_pid"
#    test -f $HOME/.sshrc && . $HOME/.sshrc
#fi
export ARCH;	
       ARCH=$(uname -m|sed -e "s/i.86/i386/")
export OS=$(uname -s)
#
# addpath() --Selectively add entries to PATH 
#
addpath() 
{
    pathvar=$1; shift
    for p in "$@"; do
        test -d "$p" && eval $pathvar='$'$pathvar:$p
    done
}

export PATH;
       PATH=.
addpath PATH $HOME/bin $HOME/bin/$OS/$ARCH
addpath PATH $HOME/local/bin $HOME/local/bin/$OS/$ARCH

addpath PATH /usr/local/bin /usr/local/sbin /usr/local/bin/X11
addpath PATH /usr/local/mysql/bin
addpath PATH /opt/local/bin /opt/local/libexec/gnubin /opt/ceos/bin
addpath PATH /bin /sbin /usr/bin /usr/sbin 
addpath PATH /usr/X11R6/bin /etc /usr/etc

addpath PATH /usr/java/bin /usr/local/java/bin

addpath PATH /cygdrive/c/WINDOWS/system32 /cygdrive/c/WINDOWS /cygdrive/c/WINDOWS/system32/Wbem
addpath PATH /usr/local/libexec /opt/ceos/libexec
addpath PATH /usr/local/home/*/bin

export PLAN9=/usr/local/plan9
addpath PATH $PLAN9/bin

export CC;
       CC=gcc
export EDITOR;
    EDITOR=vi

unset LANG
export LD_LIBRARY_PATH;
       LD_LIBRARY_PATH=$HOME/local/lib:/usr/local/lib;
addpath LD_LIBRARY_PATH /opt/local/lib
addpath LD_LIBRARY_PATH /usr/lib /usr/X11R6/lib 
export CDPATH;     
       CDPATH=.
addpath CDPATH ../ $HOME/Projects $HOME/Projects/ceos /usr/local/src

export MANPATH; 
       MANPATH=$HOME/man:$HOME/local/man:$HOME/local/share/man

addpath MANPATH /opt/ceos/share/man /opt/share/man
addpath MANPATH /usr/local/man /usr/local/teTeX/man
addpath MANPATH /usr/local/mysql/man /usr/local/share/man 
addpath MANPATH /opt/local/share/man
addpath MANPATH /usr/share/man /usr/man /usr/java/man

export HOSTNAME;
       HOSTNAME=`uname -n`

export LESS;
       LESS=-MiR
export LESSCHARSET
       LESSCHARSET=latin1
if [ -x "$HOME/bin/lesspipe" ]; then
    export LESSOPEN
           LESSOPEN="|$HOME/bin/lesspipe %s"
fi
#
# Colour options for LS:
# directory:	bold (which happens to use the "deep" colour)
# symlink:	"deep" colour
# FIFO, socket:	"deep" colour reverse video
# executable:	"bright" colour
# orphaned link, missing file:	underlined variation
# backup files:	"pale" colour
#
export LS_COLORS;
       LS_COLORS="di=1:ln=34:pi=44;37:so=44;37:ex=32:or=34;4:mi=4:*~=31"
       LS_COLORS="$LS_COLORS:ec=\e[m"

export LOG_COLORS;
       LOG_COLORS='debug=36:notice=1:warning=1;33:err=1;31:crit=1;33;41:alert=1;5;33;41:emerg=1;5;37;41'

export GREP_OPTIONS;
       GREP_OPTIONS=--color=auto
export GREP_COLOR;
       GREP_COLOR=36

export PAGER;	PAGER=less
#export SHELL;	SHELL=bash
#export TERM;	TERM=xterm
#export TMPDIR;	TMPDIR="$HOME/tmp"
export USER;	USER=${USER:-$LOGNAME}
#
# X11 setups are mostly done from the .displayrc file, which contains
# the prevailing values if a session is currently open, and doesn't
# exist when there is no current X11 session.
#
test -f "$HOME/.displayrc" && . "$HOME/.displayrc"
export XFILESEARCHPATH;
XFILESEARCHPATH="$HOME/lib/X11/1024x768/%N:/usr/X11R6/lib/X11/%T/%N"

export WIRESHARK_APP_DIR;
       WIRESHARK_APP_DIR=/Applications/Extras

#
# development settings...
#
export prefix=/usr/local
export DEVKIT_HOME=
export VCS=git

export PERL5LIB=$prefix/lib/perl5

# export CVSROOT=:ext:cvs:/home/CVS
# export CVS_RSH=ssh
export RSYNC_RSH=ssh

export LARCH_PATH=/usr/local/share/splint/lib
export LCLIMPORTDIR=/usr/local/share/splint/imports

export SVN_EDITOR=/usr/local/bin/svn-edit
export SVN_ROOT=svn+ssh://zeno/home/tirtlnet/svn
#export SVN_ROOT=http://fileserver:2178
# EOF
